name: krishiclub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  dropdown_search: ^5.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  rename: ^3.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/buyer.png
    - lib/assets/farmer.png
    - lib/assets/default_profile_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/icon.png
  