// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKw5xYxBGVjy4wLhz2D7jUwdfUp7wI3wk',
    appId: '1:1027843172882:web:ce2ec92f8666c212af86cb',
    messagingSenderId: '1027843172882',
    projectId: 'krishi-club-4315b',
    authDomain: 'krishi-club-4315b.firebaseapp.com',
    storageBucket: 'krishi-club-4315b.appspot.com',
    measurementId: 'G-DM1FP1HEJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70YVND6YqBhlOmyKig43zIhD67tHYUpA',
    appId: '1:1027843172882:android:dd9b59eac9074a4baf86cb',
    messagingSenderId: '1027843172882',
    projectId: 'krishi-club-4315b',
    storageBucket: 'krishi-club-4315b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhRQa0aaDsdy261nTsDjFireZiORxWVfA',
    appId: '1:1027843172882:ios:c55ea21e75b32898af86cb',
    messagingSenderId: '1027843172882',
    projectId: 'krishi-club-4315b',
    storageBucket: 'krishi-club-4315b.appspot.com',
    iosBundleId: 'com.pantharion.krishiclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhRQa0aaDsdy261nTsDjFireZiORxWVfA',
    appId: '1:1027843172882:ios:6638fadc2bd21c64af86cb',
    messagingSenderId: '1027843172882',
    projectId: 'krishi-club-4315b',
    storageBucket: 'krishi-club-4315b.appspot.com',
    iosBundleId: 'com.example.krishiclub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKw5xYxBGVjy4wLhz2D7jUwdfUp7wI3wk',
    appId: '1:1027843172882:web:76072be9817d3529af86cb',
    messagingSenderId: '1027843172882',
    projectId: 'krishi-club-4315b',
    authDomain: 'krishi-club-4315b.firebaseapp.com',
    storageBucket: 'krishi-club-4315b.appspot.com',
    measurementId: 'G-LCV3EBRQSG',
  );
}
